"""Add payment method to orders

Revision ID: 7170491f2c48
Revises: bd1ab8d5f8ee
Create Date: 2025-06-15 11:51:00.884852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7170491f2c48'
down_revision = 'bd1ab8d5f8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('shopify', 'paypal', 'other', 'na', name='payment_methods'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
