"""Add default_account to porviders

Revision ID: a26961c60870
Revises: 7170491f2c48
Create Date: 2025-06-15 15:38:57.046447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26961c60870'
down_revision = '7170491f2c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_providers_default_account', 'accounts', ['default_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_providers_default_account', type_='foreignkey')
        batch_op.drop_column('default_account_id')

    # ### end Alembic commands ###
