"""Add supplier_invoice to the expenses table

Revision ID: bd1ab8d5f8ee
Revises: 2ad7f412dd51
Create Date: 2025-06-14 18:04:21.548829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1ab8d5f8ee'
down_revision = '2ad7f412dd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_invoice', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_invoices', schema=None) as batch_op:
        batch_op.drop_column('supplier_invoice')

    # ### end Alembic commands ###
